**Ejercicios práctica numpy pandas**

**1.** Complete la importación con el alias convencional de la comunidad

In [128]:
import numpy as np

print(np.__version__)

2.1.3


**2.** Convierta la lista de precios en un arreglo de NumPy

In [129]:
precios = np.array([24000, 28000, 22000, 30000, 8000])

print(type(precios).__name__)
print(precios.dtype)

ndarray
int64


**3.** Averigüe la forma, el número de dimensiones y la cantidad de elementos

In [130]:
matriz = np.array([[2, 24000],
                  [1, 28000],
                   [3, 22000]])

print(matriz.shape)
print(matriz.ndim)
print(matriz.size)

(3, 2)
2
6


**4.** Genere una secuencia con paso fijo, otra con extremos fijos y un arreglo de ceros

In [131]:
secuencia = np.arange(0, 10, 2)
rango = np.linspace(0, 1, 5)
ceros = np.zeros(5)

print(secuencia)
print(rango)
print(ceros.dtype)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
float64


**5.** Corrige

In [132]:
precios = np.array([24000, 28000, 22000])


Faltaba [] porque la función esperaba recibir una lista

**6.** Calcule el ingreso de cada transacción multiplicando elemento por elemento

In [133]:
cantidades = np.array([2, 1, 3, 2, 1])
precios = np.array([24000, 28000, 22000, 30000, 8000])

ingresos = cantidades * precios

print(ingresos)

[48000 28000 66000 60000  8000]


**7.** Aplique un descuento del diez por ciento a todos los precios

In [134]:
con_descuento = precios * 0.9

print(con_descuento)
print(con_descuento.dtype)

[21600. 25200. 19800. 27000.  7200.]
float64


**8.** Escriba con NumPy lo que el ciclo hace con listas

In [135]:
# con listas de Python
lista  = np.array([24000, 28000, 22000, 30000, 8000])
resultado = []
for p in lista:
  resultado.append(p * 1.19)

# con NumPy, en una sola línea
resultado_np = lista * 1.19
print(resultado_np)

[28560. 33320. 26180. 35700.  9520.]


**9.** El mismo operador sobre dos estructuras distintas

In [136]:
lista = [1, 2, 3]
arreglo = np.array([1, 2, 3])

print(lista * 2)
print(arreglo * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


sobre una lista lo que hace es escribir dos veces lo que esté en la lista...mientras que en un arreglo NumPy multiplica cada valor por el número 2

**10.** Un arreglo de cinco elementos multiplicado por uno de cuatro

In [137]:
a = np.array([2, 1, 3, 2, 1])
b = np.array([10, 20, 30, 40])


Predicción: error


Resultado: Lanza error, ValueError: operands could not be broadcast together with shapes (5,) (4,)

**11.** El bloque funciona, pero desaprovecha Numpy por completo

In [138]:
ingresos = np.zeros(5)

ingresos = cantidades * precios
print(ingresos)


[48000 28000 66000 60000  8000]


se gana 3 cosas: aprovechamos NumPy, eficiencia computacional y se escribe menos

**12.** Obtenga elementos por posición sin contar cuántos hay

In [139]:
print(precios[0])
print(precios[-1])
print(precios[1:4])

24000
8000
[28000 22000 30000]


**13.** Construya la condición y úsela para filtrar

In [140]:
mascara = precios > 20000

print(mascara)
print(precios[mascara])
print(precios[mascara].sum())

[ True  True  True  True False]
[24000 28000 22000 30000]
104000


**14.** Precios mayores a 10000 y menores a 29000. Recuerde el operador correcto

In [141]:
selección = precios[(precios > 10000) & (precios < 29000)]

print(selección)

[24000 28000 22000]


**15.** Clasifique cada precio sin escribir un ciclo ni un if

In [142]:
etiquetas = np.where(precios > 25000, "alto", "normal")

print(etiquetas)

['normal' 'alto' 'normal' 'alto' 'normal']


**16.** Cuántos elementos cumplen la condición y cuánto suman

In [143]:
caros = precios[precios > 20000]

print(caros.size)
print(caros.sum())

4
104000


**17.** Corrige

In [144]:
selección = precios [(precios > 10000) & (precios < 29000)]
print(selección)

[24000 28000 22000]


**18.** Complete cada línea con el método que corresponde

In [145]:
ingresos = np.array([48000, 28000, 66000, 60000, 8000])

print(ingresos.sum())
print(ingresos.mean())
print(ingresos.max())
print(round(ingresos.std(), 2))

210000
42000.0
66000
21391.59


**19.** Cada fila es un producto y cada columna una sede. Obtenga el total de cada sede

In [146]:
matriz = np.array([[48000, 28000],
                   [66000, 60000],
                   [8000, 12000]])

print(matriz.sum(axis=0))

[122000 100000]


**20.** Ahora el total de cada producto y el total general

In [147]:
print(matriz.sum(axis=1))
print(matriz.sum())

[ 76000 126000  20000]
222000


**21.** Sin ejecutar nada todavía, escriba su predicción y después compruébela

In [148]:
print(matriz.mean(axis=0))

[40666.66666667 33333.33333333]


Es el promedio de cada columna

**22.** Convierta la lista de diccionarios del caso en una tabla y revise su estructura

In [149]:
import pandas as pd
#datos_ventas="datos_ventas.csv"
datos_ventas= "https://raw.githubusercontent.com/Maria-Alejandra-Soto-Escobar/Actividad_4/refs/heads/main/datos_ventas.csv"
df_ventas = pd.read_csv(datos_ventas, sep=";")

print(df_ventas.shape)
print(df_ventas.head(3))



(19, 8)
       fecha  cliente      producto categoria  cantidad precio_unitario  \
0  3/08/2026      101   Bowl Andino  Almuerzo         2       24.000,00   
1  3/08/2026      102  Pasta Urbana  Almuerzo         1       28.000,00   
2  4/08/2026      103   Bowl Andino  Almuerzo         1       24.000,00   

  costo_unitario     sede  
0      14.000,00   centro  
1      17.000,00    NORTE  
2      14.000,00  Centro   


In [150]:
#Conversión de formato de fecha
df_ventas["fecha"] = pd.to_datetime(df_ventas["fecha"], format="mixed")
df_ventas.head()

,fecha,cliente,producto,categoria,cantidad,precio_unitario,costo_unitario,sede
0,2026-03-08,101,Bowl Andino,Almuerzo,2,"24.000,00","14.000,00",centro
1,2026-03-08,102,Pasta Urbana,Almuerzo,1,"28.000,00","17.000,00",NORTE
2,2026-04-08,103,Bowl Andino,Almuerzo,1,"24.000,00","14.000,00",Centro
3,2026-04-08,103,Bowl Andino,Almuerzo,1,"24.000,00","14.000,00",Centro
4,2026-04-08,104,Hamburguesa Central,Cena,2,"30.000,00","19.000,00",Norte


**23.** Complete los corchetes para obtener primero una serie y después un DataFrame

In [151]:
una = df_ventas["producto"]

varias = df_ventas[["producto", "cantidad"]]

print(type(una).__name__, type(varias).__name__)

Series DataFrame


**24.** Pandas está construido sobre NumPy. Compruébelo

In [152]:
arreglo = df_ventas["cantidad"].to_numpy()

print(type(arreglo).__name__)
print(arreglo.sum())

ndarray
32


**Mi respuesta:** to_numpy() devuelve un objeto de tipo ndarray, ya que convierte la columna de Pandas en un arreglo de NumPy. Luego, con .sum() se suman todas las cantidades almacenadas en ese arreglo.

**25.** Dos formas de localizar filas. dos resultados distintos

In [153]:
print(df_ventas.loc[0:2].shape[0]) #incluye
print(df_ventas.iloc[0:2].shape[0]) #no incluye


3
2


**26.** Filtrar con dos condiciones

In [154]:
mascara = (
    (df_ventas["sede"] == "Centro")
    & (df_ventas["categoria"] == "Almuerzo")
)

seleccion = df_ventas.loc[mascara].copy()

print(seleccion.shape[0], seleccion["cantidad"].sum())

3 7


**27.** Cree las tres columnas que permiten hablar de rentabilidad

In [156]:
df_ventas["precio_unitario"] = pd.to_numeric(
    df_ventas["precio_unitario"]
        .astype(str)
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False),
    errors="coerce"
)

df_ventas["costo_unitario"] = pd.to_numeric(
    df_ventas["costo_unitario"]
        .astype(str)
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False),
    errors="coerce"
)

df_ventas["ingreso"] = df_ventas["cantidad"] * df_ventas["precio_unitario"]
df_ventas["costo_total"] = df_ventas["cantidad"] * df_ventas["costo_unitario"]
df_ventas["margen_bruto"] = df_ventas["ingreso"] - df_ventas["costo_total"]

print(df_ventas["ingreso"].sum(), df_ventas["margen_bruto"].sum())

730000.0 282000.0


**28.** Indicadores globales

In [157]:
ingreso_total = df_ventas["ingreso"].sum()
margen_total = df_ventas["margen_bruto"].sum()

porcentaje_global = round(margen_total / ingreso_total * 100, 2)
ticket_promedio = round(ingreso_total / len(df_ventas), 2)

print(porcentaje_global, ticket_promedio)

38.63 38421.05


**29.** Agrupar por producto

In [158]:
kpi = (
    df_ventas
    .groupby("producto")
    .agg(
        ingreso=("ingreso", "sum"),
        margen=("margen_bruto", "sum"),
    )
    .reset_index()
)

kpi["porcentaje_margen"] = (kpi["margen"] / kpi["ingreso"] * 100).round(2)

print(kpi)

              producto   ingreso    margen  porcentaje_margen
0          Bowl Andino  264000.0  110000.0              41.67
1  Ensalada de la Casa  110000.0   40000.0              36.36
2  Hamburguesa Central  120000.0   44000.0              36.67
3     Limonada Natural   40000.0   11000.0              27.50
4         Pasta Urbana  196000.0   77000.0              39.29


**30.** Reto integrador: el resumen ejecutivo

In [160]:
def resumen_ejecutivo(df):
    ingreso = df["ingreso"].sum()
    margen = df["margen_bruto"].sum()

    return {
        "total_ingresos": float(ingreso),
        "margen_bruto": float(margen),
        "porcentaje_margen": round(float(margen / ingreso * 100), 2),
        "ticket_promedio": round(float(ingreso / len(df)), 2),
    }

print(resumen_ejecutivo(df_ventas))

solo_centro = df_ventas[df_ventas["sede"] == "Centro"].copy()
print(resumen_ejecutivo(solo_centro))

{'total_ingresos': 730000.0, 'margen_bruto': 282000.0, 'porcentaje_margen': 38.63, 'ticket_promedio': 38421.05}
{'total_ingresos': 168000.0, 'margen_bruto': 70000.0, 'porcentaje_margen': 41.67, 'ticket_promedio': 56000.0}
